export function downloadAsMarkdown(
  content: string,
  filename = "resume-optimization.md"
): void {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.style.display = "none";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up the URL object
  URL.revokeObjectURL(url);
}

export function formatOptimizationAsMarkdown(
  jobTitle: string,
  companyName: string,
  summary: string,
  bullets: string[],
  coverLetter: string
): string {
  return `# Resume Optimization for ${jobTitle} at ${companyName}
  
  ## Summary
  ${summary}
  
  ## Tailored Resume Bullets
  ${bullets.map((bullet) => `- ${bullet}`).join("\n")}
  
  ## Cover Letter
  ${coverLetter}
  
  ---
  *Generated by AI Job Optimizer*
  `;
}
